v1.0.0

diff --git a/bin/sail b/bin/sail
--- a/bin/sail
+++ b/bin/sail
@@ -10,7 +10,7 @@ case "${UNAMEOUT}" in
 esac
 
 if [ "$MACHINE" == "UNKNOWN" ]; then
-    echo "Unsupported operating system [$(uname -s)]. QuantaQuirk Sail supports macOS, Linux, and Windows (WSL2)." >&2
+    echo "Unsupported operating system [$(uname -s)]. QuantaForge Sail supports macOS, Linux, and Windows (WSL2)." >&2
 
     exit 1
 fi
@@ -30,7 +30,7 @@ fi
 
 # Function that prints the available commands...
 function display_help {
-    echo "QuantaQuirk Sail"
+    echo "QuantaForge Sail"
     echo
     echo "${YELLOW}Usage:${NC}" >&2
     echo "  sail COMMAND [options] [arguments]"
@@ -54,7 +54,7 @@ function display_help {
     echo
     echo "${YELLOW}Composer Commands:${NC}"
     echo "  ${GREEN}sail composer ...${NC}                       Run a Composer command"
-    echo "  ${GREEN}sail composer require quantaquirk/sanctum${NC}"
+    echo "  ${GREEN}sail composer require quantaforge/sanctum${NC}"
     echo
     echo "${YELLOW}Node Commands:${NC}"
     echo "  ${GREEN}sail node ...${NC}         Run a Node command"
@@ -94,15 +94,15 @@ function display_help {
     echo "  ${GREEN}sail phpunit ...${NC}   Run PHPUnit"
     echo "  ${GREEN}sail pest ...${NC}      Run Pest"
     echo "  ${GREEN}sail pint ...${NC}      Run Pint"
-    echo "  ${GREEN}sail dusk${NC}          Run the Dusk tests (Requires the quantaquirk/dusk package)"
-    echo "  ${GREEN}sail dusk:fails${NC}    Re-run previously failed Dusk tests (Requires the quantaquirk/dusk package)"
+    echo "  ${GREEN}sail dusk${NC}          Run the Dusk tests (Requires the quantaforge/dusk package)"
+    echo "  ${GREEN}sail dusk:fails${NC}    Re-run previously failed Dusk tests (Requires the quantaforge/dusk package)"
     echo
     echo "${YELLOW}Container CLI:${NC}"
     echo "  ${GREEN}sail shell${NC}        Start a shell session within the application container"
     echo "  ${GREEN}sail bash${NC}         Alias for 'sail shell'"
     echo "  ${GREEN}sail root-shell${NC}   Start a root shell session within the application container"
     echo "  ${GREEN}sail root-bash${NC}    Alias for 'sail root-shell'"
-    echo "  ${GREEN}sail tinker${NC}       Start a new QuantaQuirk Tinker session"
+    echo "  ${GREEN}sail tinker${NC}       Start a new QuantaForge Tinker session"
     echo
     echo "${YELLOW}Sharing:${NC}"
     echo "  ${GREEN}sail share${NC}   Share the application publicly via a temporary URL"
@@ -127,7 +127,7 @@ else
     display_help
 fi
 
-# Source the ".env" file so QuantaQuirk's environment variables are available...
+# Source the ".env" file so QuantaForge's environment variables are available...
 if [ ! -z "$APP_ENV" ] && [ -f ./.env.$APP_ENV ]; then
   source ./.env.$APP_ENV;
 elif [ -f ./.env ]; then
@@ -136,14 +136,14 @@ fi
 
 # Define environment variables...
 export APP_PORT=${APP_PORT:-80}
-export APP_SERVICE=${APP_SERVICE:-"quantaquirk.test"}
+export APP_SERVICE=${APP_SERVICE:-"quantaforge.test"}
 export DB_PORT=${DB_PORT:-3306}
 export WWWUSER=${WWWUSER:-$UID}
 export WWWGROUP=${WWWGROUP:-$(id -g)}
 
 export SAIL_FILES=${SAIL_FILES:-""}
 export SAIL_SHARE_DASHBOARD=${SAIL_SHARE_DASHBOARD:-4040}
-export SAIL_SHARE_SERVER_HOST=${SAIL_SHARE_SERVER_HOST:-"quantaquirk-sail.site"}
+export SAIL_SHARE_SERVER_HOST=${SAIL_SHARE_SERVER_HOST:-"quantaforge-sail.site"}
 export SAIL_SHARE_SERVER_PORT=${SAIL_SHARE_SERVER_PORT:-8080}
 export SAIL_SHARE_SUBDOMAIN=${SAIL_SHARE_SUBDOMAIN:-""}
 export SAIL_SHARE_DOMAIN=${SAIL_SHARE_DOMAIN:-"$SAIL_SHARE_SERVER_HOST"}
@@ -353,7 +353,7 @@ elif [ "$1" == "dusk:fails" ]; then
         sail_is_not_running
     fi
 
-# Initiate a QuantaQuirk Tinker session within the application container...
+# Initiate a QuantaForge Tinker session within the application container...
 elif [ "$1" == "tinker" ] ; then
     shift 1
 
